### ISSUE TITLE
Feature Suggestion: Event Listener on Document Body

### ISSUE THREAD

**Issue by SterlingButters** [jimmybow/mydcc#4]
Would this be easily accomplishable?

**Comment by jimmybow** [comment]
you can try visdcc.Run_js to run your javascript
https://github.com/jimmybow/visdcc#3-visdccrun_js-

**Comment by jimmybow** [comment]
here is the example for adding event listener https://github.com/jimmybow/visdcc/blob/master/example/Run_js/Add_event_and_callback.py

**Comment by SterlingButters** [comment]
Thanks! I'll check it out!
